### PR TITLE
Move README to markdown format.

### PR DESCRIPTION
**Pull request by rspier**
Markdown is a *lot* more popular than reStructuredText[1], so potential committers will be more familiar with it.  There are enough similarities and differences that it's easy to trip up.

(If you feel strongly about reST, feel free to reject this pull request.  It's not a big deal.)

[1] on GitHub and in Google Trends (https://trends.google.com/trends/explore?q=markdown,RestructuredText)

### CODE REVIEW

**Comment by Bennyoak** [comment]
My main reason for running with reST is because the README looks jacked up on pypi otherwise. I'm open to alternatives tho.

**Comment by rspier** [comment]
That's a very good reason.

I've updated the CL based on 
https://bitbucket.org/pypa/pypi/issues/148/support-markdown-for-readmes and https://github.com/pypa/pypi-legacy/issues/148

It looks like it's quite a contentious thing, and this solution is a little hacky, but it works.  If it's too hacky for you, I'll let it go.

**Comment by Bennyoak** [comment]
I think this is something that can wait. Github seems to be OK with reST at the moment along with pypi. The best solution might just be to write a converter into the setup config using pandoc or the like.

**Comment by rspier** [comment]
That's what the latest version does.

But I agree. This is not important. It impulsively came out of being frustrated with reST.

**Comment by Bennyoak** [comment]
Haha - yeah I can understand that. IMO readme's are static enough that it doesn't bother me to write it in whatever format is needed.

btw - I've updated pypi. DCN 1.0.0 is now pip installable!

**Comment by rspier** [comment]
That's rational.  I'll close this request for now.

Congrats on 1.0.0!

**Pull request closed without merging**
